### ISSUE TITLE
REGEX: Email

### ISSUE THREAD

**Issue by ljosberinn** [DrRoach/FormValidation#3]
There's a lengthy and read-worthy discussion about REGEX Mail patterns [here](http://emailregex.com/#disqus_thread).

Basically, 

```
if(val.match(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i) != null) {
     addSuccess(this);
}
```

marks **for example** blocks custom endings beyond 4 characters as invalid.

[Some](https://github.com/plataformatec/devise/blob/18b6064d74726147eccd69b24812000074261bbb/lib/generators/templates/devise.rb#L151-L154) even go as far and only check for an @ sign existing in the string

**Comment by DrRoach** [comment]
Thanks for the interesting read!

I'm going to change the current regex to use the one advised in the article that you linked and also add some form of flag that switches the filter to just `@`.

Will implement this either today or tomorrow

**Comment by DrRoach** [comment]
Updated the email regex to use to one from the site that @ljosberinn linked.

Also added `fv-simple-email` that only checks to make sure that `@` is in the input.

Commit: 627e529c2095c2ddc4bad962bec613b944939bfc
