### ISSUE TITLE
Possible to run function if valid?

### ISSUE THREAD

**Issue by seanvree** [DrRoach/FormValidation#6]
hey buddy - question. 

Would it be possible to run a function or simply apply a JS variable if the input field is validated?

For example, if the field was valid to "addClass" or something similar?

In this case the sumbit button would be hidden if not validated, or vice versa:

```
$('#datadirbtn').addClass("btn-hidden");
```

thx!

**Comment by DrRoach** [comment]
This has now been added in 566c7caa193b48f0b092237a840213e1a3b2acbc.

You can add the `fv-valid-func` and `fv-invalid-func` data attributes to execute custom JS on validation/invalidation. For a better explanation of use please see the [README](https://github.com/DrRoach/FormValidation).

On a side not as of this version (v1.1.0) there are no more uses of `eval()` so the project should be quicker and more secure.

**Comment by seanvree** [comment]
@DrRoach  you're the man!
